import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useRouter } from "next/router";

const Reiseforsikring: NextPage = () => {
  const router = useRouter();

    const customer = {
        name: "Per Andreas Hansen",
        contract: 123456789,
        monthlyPrice: 249,
        from_date: "01.01.2021",
        end_date: "01.01.2022",
        contract_pdf: "/avtale.pdf"
    }

  return (
    <div className={styles.container}>
      <Head>
        <title>Reiseforsikring</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.top}>
        <h2 className={styles.title}>
        Reiseforsikring
        </h2>
        <p>{customer.name}</p>
        </div>

        <div className={styles.fakturaoversikt}>
            <div className={styles.fakturaTop}>
            <h4>Du betaler {customer.monthlyPrice} kr/mnd</h4>
            <p className={styles.link} onClick={() => router.push('/faktura')}>Fakturaoversikt →</p>
            </div>
            <div className={styles.fakturaLine}>
                <h5>Periode</h5>
                <p>{customer.from_date} - {customer.end_date}</p>
            </div>
            <div className={styles.fakturaLine}>
                <h5>Avtalenummer</h5>
                <p>{customer.contract}</p>
            </div>
            <div className={styles.fakturaLine}>
                <h5>Dokument</h5>
                <a href={customer.contract_pdf} rel="noreferrer" target={"_blank"}>Avtaledokument (PDF) ↗</a>
            </div>
        </div>
        <div className={styles.coverIMG}/>
      </main>
    </div>
  )
}

export default Reiseforsikring
